services:
  adnet-brain:
    build:
      context: src/
      dockerfile: Dockerfile-brain
      target: adnet-brain
    image: adnet-brain
    volumes:
      - "./:/repo/"
      - "/mnt/d/ADNI:/mnt/d/ADNI"  # Mapeia o diretório do HD externo
      - "/mnt/e/ADNI:/mnt/e/ADNI"

  adnet-cnn:
    build:
      context: src/
      dockerfile: Dockerfile-cnn
      target: adnet-cnn
    image: adnet-cnn
    volumes:
      - "./:/repo/"
      - "/mnt/d/ADNI:/mnt/d/ADNI"  # Mapeia o diretório do HD externo
      - "/mnt/e/ADNI:/mnt/e/ADNI"
